2021-05-18 20:50:52 - INFO - Failed login
2021-05-18 20:50:57 - INFO - Failed login
2021-05-18 20:51:04 - INFO - Failed login
2021-05-18 20:52:19 - INFO - login education
2021-05-18 20:52:50 - INFO - course added
NoneType: None
2021-05-18 21:35:29 - INFO - course added
NoneType: None
2021-05-18 21:36:03 - INFO - course added
NoneType: None
2021-05-18 21:36:41 - INFO - course added
NoneType: None
2021-05-18 21:37:09 - INFO - course added
NoneType: None
2021-05-18 21:37:46 - INFO - course added
NoneType: None
2021-05-18 21:38:36 - INFO - login student
2021-05-18 21:39:05 - INFO - selection unit successful
2021-05-18 21:39:37 - INFO - remove course successful
2021-05-18 21:40:05 - INFO - login education
2021-05-18 21:41:03 - INFO - login student
2021-05-18 21:41:09 - INFO - selection unit successful
2021-05-18 21:46:46 - INFO - remove course successful
2021-05-18 21:47:04 - INFO - login student
2021-05-18 21:47:53 - ERROR - mistake item
Traceback (most recent call last):
  File "C:/Users/Allah/PycharmProjects/Test_Project/main.py", line 27, in menu_student
    assert slc_item in ['1', '2', '3', '4', '5']
AssertionError
2021-05-18 21:48:04 - INFO - login education
2021-05-18 21:48:23 - ERROR - mistake item
Traceback (most recent call last):
  File "C:/Users/Allah/PycharmProjects/Test_Project/main.py", line 86, in menu_education
    status_crs = obj_edu.create_course(course)  # enter information course
  File "C:\Users\Allah\PycharmProjects\Test_Project\Education.py", line 17, in create_course
    obj_course = Course(*crs)
TypeError: __init__() missing 1 required positional argument: 'field_crs'
2021-05-18 21:49:05 - ERROR - mistake item
Traceback (most recent call last):
  File "C:/Users/Allah/PycharmProjects/Test_Project/main.py", line 86, in menu_education
    status_crs = obj_edu.create_course(course)  # enter information course
  File "C:\Users\Allah\PycharmProjects\Test_Project\Education.py", line 17, in create_course
    obj_course = Course(*crs)
TypeError: __init__() missing 1 required positional argument: 'field_crs'
2021-05-18 21:49:25 - INFO - course added
NoneType: None
2021-05-18 21:49:43 - INFO - course added
NoneType: None
2021-05-18 21:50:15 - INFO - course added
NoneType: None
2021-05-18 21:50:31 - INFO - login student
2021-05-18 21:50:59 - ERROR - mistake item
Traceback (most recent call last):
  File "C:/Users/Allah/PycharmProjects/Test_Project/main.py", line 27, in menu_student
    assert slc_item in ['1', '2', '3', '4', '5']
AssertionError
2021-05-18 21:51:06 - ERROR - capacity course 4 full or enter id course mistake
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 104, in get_course
    assert obj_crs.capacity > obj_crs.status_capacity and obj_crs.field_crs == self.field
AssertionError
2021-05-18 21:53:08 - INFO - login student
2021-05-18 21:53:27 - ERROR - capacity course 6 full or enter id course mistake
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 104, in get_course
    assert obj_crs.capacity > obj_crs.status_capacity and obj_crs.field_crs == self.field
AssertionError
2021-05-18 21:54:52 - INFO - login student
2021-05-18 21:54:57 - INFO - selection unit successful
2021-05-18 21:55:19 - INFO - login education
2021-05-18 21:57:13 - INFO - login education
2021-05-18 21:57:42 - INFO - login student
2021-05-18 21:59:01 - ERROR - mistake item
Traceback (most recent call last):
  File "C:/Users/Allah/PycharmProjects/Test_Project/main.py", line 27, in menu_student
    assert slc_item in ['1', '2', '3', '4', '5']
AssertionError
2021-05-18 21:59:09 - ERROR - Number of units is not allowed
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 110, in get_course
    assert 20 >= sum_unit >= 10
AssertionError
2021-05-18 21:59:44 - INFO - login student
2021-05-18 21:59:49 - ERROR - Number of units is not allowed
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 110, in get_course
    assert 20 >= sum_unit >= 10
AssertionError
2021-05-18 21:59:54 - ERROR - capacity course 4 full or enter id course mistake
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 104, in get_course
    assert obj_crs.capacity > obj_crs.status_capacity and obj_crs.field_crs == self.field or obj_crs.field_crs == 'public'
AssertionError
2021-05-18 22:00:34 - ERROR - mistake item
Traceback (most recent call last):
  File "C:/Users/Allah/PycharmProjects/Test_Project/main.py", line 27, in menu_student
    assert slc_item in ['1', '2', '3', '4', '5']
AssertionError
2021-05-18 22:00:40 - INFO - selection unit successful
2021-05-18 22:02:53 - INFO - remove course successful
2021-05-18 22:09:50 - INFO - login education
2021-05-18 22:12:49 - INFO - login education
2021-05-18 22:13:33 - ERROR - Number of units is not allowed
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 158, in remove_crs
    assert sum_unit > 0
AssertionError
2021-05-18 22:15:27 - INFO - login student
2021-05-18 22:17:09 - INFO - login student
2021-05-18 22:18:58 - INFO - login student
2021-05-19 08:39:22 - INFO - login education
2021-05-19 08:40:54 - INFO - Failed login
2021-05-19 08:41:10 - INFO - login education
2021-05-19 08:49:45 - INFO - login education
2021-05-19 13:34:40 - INFO - login education
2021-05-19 14:00:21 - INFO - login education
2021-05-19 14:06:11 - ERROR - mistake item
Traceback (most recent call last):
  File "C:/Users/Allah/PycharmProjects/Test_Project/main.py", line 88, in menu_education
    assert slc_item in ['1', '2', '3', '4']
AssertionError
2021-05-19 14:07:45 - INFO - course added
NoneType: None
2021-05-19 14:20:45 - INFO - login education
2021-05-19 14:22:36 - INFO - course added
NoneType: None
2021-05-19 14:24:10 - INFO - login student
2021-05-19 14:26:34 - ERROR - Number of units is not allowed
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 111, in get_course
    assert 20 >= sum_unit >= 10
AssertionError
2021-05-19 14:27:08 - ERROR - capacity course 4 full or enter id course mistake
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 105, in get_course
    assert obj_crs.capacity > obj_crs.status_capacity and obj_crs.field_crs == self.field or obj_crs.field_crs == 'public'
AssertionError
2021-05-19 14:27:25 - INFO - selection unit successful
2021-05-19 14:32:11 - INFO - remove course successful
2021-05-19 14:33:49 - INFO - login education
2021-05-19 14:34:59 - INFO - login student
2021-05-19 14:35:17 - ERROR - Number of units is not allowed
Traceback (most recent call last):
  File "C:\Users\Allah\PycharmProjects\Test_Project\Student.py", line 111, in get_course
    assert 20 >= sum_unit >= 10
AssertionError
2021-05-19 14:35:49 - INFO - login student
2021-05-19 14:36:07 - INFO - selection unit successful
